version: '3.3'

services:

  database:
    image: mysql:5.6
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./sklad:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sklad

  flaskapp:
    build:
      context: ./docker/app
    container_name: flaskapp
    restart: always
    ports:
      - "5001:5000"
    environment:
      - DATABASE_HOST=database    ## Container name of Mysql
      - DATABASE_PORT=3306
      - MYSQL_ROOT_PASSWORD=root

volumes:
  sklad:
  mysql:
