version: '3.3'

services:

  mysql:
    container_name: sklad-mysql
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: sklad
      MYSQL_USER: sklad
      MYSQL_PASSWORD: 123123

  flaskapp:
    build:
      context: ./docker/app
    container_name: flaskapp
    restart: always
    ports:
      - "5001:5000"
    environment:
      - DATABASE_HOST=sklad-mysql    ## Container name of Mysql
      - DATABASE_PORT=3306
      - MYSQL_ROOT_PASSWORD=root

volumes:
  sklad:
  mysql:
